import React, { useState, useEffect, useRef } from 'react';
import { 
  ShieldAlert, 
  UploadCloud, 
  History, 
  Download, 
  Stethoscope, 
  Activity, 
  ChevronRight, 
  Info, 
  Moon, 
  Sun, 
  Globe, 
  Trash2, 
  Loader2, 
  CheckCircle, 
  AlertTriangle,
  FileText,
  Eye,
  Plus
} from 'lucide-react';

const API_BASE = 'http://localhost:5000/api';

// Multi-language translation dictionary for dashboard UI
const TRANSLATIONS = {
  en: {
    appTitle: "HealthDecode",
    appSubtitle: "Medical Second-Opinion Assistant",
    disclaimer: "This tool is for educational purposes only and is not a substitute for professional medical advice, diagnosis, or treatment. Always consult with qualified healthcare professionals.",
    uploadZone: "Drag and drop your medical files here, or click to browse",
    uploadFormats: "Supports PDF reports and images (X-ray, MRI, CT, Ultrasound, Lab Results)",
    uploadingText: "Extracting text and running MedGemma analysis...",
    btnAnalyze: "Analyze Document",
    btnNewUpload: "Upload New Report",
    historyTitle: "Report History",
    noHistory: "No reports analyzed yet",
    tabSummary: "AI Summary",
    tabObservations: "Visual Findings",
    tabFindings: "Key Findings",
    tabAbnormals: "Abnormal Values",
    tabTerminology: "Medical Terms",
    tabDoctorPrep: "Doctor Prep",
    lblNormal: "Normal Range",
    lblValue: "Observed Value",
    lblInterpretation: "Explanation",
    btnExportPdf: "Download Summary PDF",
    btnExportSheet: "Doctor Discussion Sheet",
    placeholderChoose: "Upload or select a report from the history sidebar to begin analysis.",
    lblDate: "Date Analyzed",
    lblFileType: "File Type",
    disclaimerConfidence: "Visual observations are generated by AI analysis of patterns and should be validated by a board-certified radiologist.",
    lblAbnormalDetected: "Out-of-range parameters identified",
    secSymptoms: "Symptoms to Mention",
    secQuestions: "Discussion Questions",
    secObservations: "Key Findings Checklist"
  },
  es: {
    appTitle: "HealthDecode",
    appSubtitle: "Asistente Médico de Segunda Opinión",
    disclaimer: "Esta herramienta tiene únicamente fines educativos y no sustituye el consejo, diagnóstico o tratamiento médico profesional. Consulte siempre con profesionales de la salud calificados.",
    uploadZone: "Arrastre y suelte sus archivos médicos aquí, o haga clic para buscar",
    uploadFormats: "Soporta informes PDF e imágenes (Rayos X, RM, TC, Ecografía, Análisis de sangre)",
    uploadingText: "Extrayendo texto y ejecutando análisis de MedGemma...",
    btnAnalyze: "Analizar Documento",
    btnNewUpload: "Subir Nuevo Informe",
    historyTitle: "Historial de Informes",
    noHistory: "Ningún informe analizado aún",
    tabSummary: "Resumen IA",
    tabObservations: "Hallazgos Visuales",
    tabFindings: "Puntos Clave",
    tabAbnormals: "Valores Anómalos",
    tabTerminology: "Términos Médicos",
    tabDoctorPrep: "Preparar Consulta",
    lblNormal: "Rango Normal",
    lblValue: "Valor Observado",
    lblInterpretation: "Explicación",
    btnExportPdf: "Descargar PDF de Resumen",
    btnExportSheet: "Guía de Discusión Médica",
    placeholderChoose: "Suba o seleccione un informe del historial lateral para comenzar el análisis.",
    lblDate: "Fecha de Análisis",
    lblFileType: "Tipo de Archivo",
    disclaimerConfidence: "Las observaciones visuales son generadas por análisis de patrones por IA y deben ser validadas por un radiólogo colegiado.",
    lblAbnormalDetected: "Parámetros fuera de rango identificados",
    secSymptoms: "Síntomas a Mencionar",
    secQuestions: "Preguntas de Discusión",
    secObservations: "Lista de Verificación de Hallazgos"
  },
  fr: {
    appTitle: "HealthDecode",
    appSubtitle: "Assistant Médical de Deuxième Avis",
    disclaimer: "Cet outil est destiné uniquement à des fins éducatives et ne remplace pas un avis médical professionnel, un diagnostic ou un traitement. Consultez toujours un professionnel de la santé qualifié.",
    uploadZone: "Glissez et déposez vos fichiers médicaux ici, ou cliquez pour parcourir",
    uploadFormats: "Prend en charge les rapports PDF et les images (Radiographie, IRM, Scanner, Échographie, Analyses)",
    uploadingText: "Extraction du texte et analyse MedGemma en cours...",
    btnAnalyze: "Analyser le Document",
    btnNewUpload: "Transférer un nouveau rapport",
    historyTitle: "Historique des Rapports",
    noHistory: "Aucun rapport analysé pour le moment",
    tabSummary: "Résumé IA",
    tabObservations: "Observations Visuelles",
    tabFindings: "Points Clés",
    tabAbnormals: "Valeurs Anormales",
    tabTerminology: "Termes Médicaux",
    tabDoctorPrep: "Préparer la Visite",
    lblNormal: "Valeurs de Référence",
    lblValue: "Valeur Observée",
    lblInterpretation: "Explication",
    btnExportPdf: "Télécharger le PDF de Résumé",
    btnExportSheet: "Guide de Discussion Médicale",
    placeholderChoose: "Téléversez ou sélectionnez un rapport dans l'historique pour commencer l'analyse.",
    lblDate: "Date d'Analyse",
    lblFileType: "Type de Fichier",
    disclaimerConfidence: "Les observations visuelles sont générées par analyse de motifs IA et doivent être validées par un radiologue qualifié.",
    lblAbnormalDetected: "Paramètres hors normes détectés",
    secSymptoms: "Symptômes à Signaler",
    secQuestions: "Questions de Discussion",
    secObservations: "Liste des Observations"
  },
  de: {
    appTitle: "HealthDecode",
    appSubtitle: "Medizinischer Zweitmeinungs-Assistent",
    disclaimer: "Dieses Tool dient ausschließlich Bildungszwecken und ersetzt keine professionelle medizinische Beratung, Diagnose oder Behandlung. Fragen Sie immer Ihren Arzt.",
    uploadZone: "Ziehen Sie Ihre medizinischen Dateien hierher oder klicken Sie zum Auswählen",
    uploadFormats: "Unterstützt PDF-Berichte und Bilder (Röntgen, MRT, CT, Ultraschall, Laborbefunde)",
    uploadingText: "Text wird extrahiert und MedGemma-Analyse läuft...",
    btnAnalyze: "Dokument analysieren",
    btnNewUpload: "Neuen Bericht hochladen",
    historyTitle: "Berichtsverlauf",
    noHistory: "Noch keine Berichte analysiert",
    tabSummary: "KI-Zusammenfassung",
    tabObservations: "Visuelle Befunde",
    tabFindings: "Hauptbefunde",
    tabAbnormals: "Abweichende Werte",
    tabTerminology: "Fachbegriffe",
    tabDoctorPrep: "Arztbesuch Vorbereitung",
    lblNormal: "Referenzbereich",
    lblValue: "Beobachteter Wert",
    lblInterpretation: "Erklärung",
    btnExportPdf: "Zusammenfassung als PDF herunterladen",
    btnExportSheet: "Leitfaden für das Arztgespräch",
    placeholderChoose: "Laden Sie einen Bericht hoch oder wählen Sie einen aus dem Verlauf aus, um die Analyse zu starten.",
    lblDate: "Analysedatum",
    lblFileType: "Dateityp",
    disclaimerConfidence: "Visuelle Beobachtungen basieren auf KI-Mustererkennung und sollten von einem zertifizierten Radiologen überprüft werden.",
    lblAbnormalDetected: "Außerhalb des Referenzbereichs liegende Parameter identifiziert",
    secSymptoms: "Zu erwähnende Symptome",
    secQuestions: "Diskussionsfragen",
    secObservations: "Befund-Checkliste"
  }
};

export default function App() {
  const [lang, setLang] = useState('en');
  const [darkMode, setDarkMode] = useState(false);
  
  const [history, setHistory] = useState([]);
  const [selectedReport, setSelectedReport] = useState(null);
  const [loading, setLoading] = useState(false);
  const [activeTab, setActiveTab] = useState('summary');
  const [dragActive, setDragActive] = useState(false);
  
  const fileInputRef = useRef(null);
  const t = TRANSLATIONS[lang];

  // Fetch report history on load
  useEffect(() => {
    fetchHistory();
  }, []);

  // Update body dark mode class
  useEffect(() => {
    if (darkMode) {
      document.body.classList.add('dark');
    } else {
      document.body.classList.remove('dark');
    }
  }, [darkMode]);

  const fetchHistory = async () => {
    try {
      const res = await fetch(`${API_BASE}/history`);
      if (res.ok) {
        const data = await res.json();
        setHistory(data);
      }
    } catch (err) {
      console.error("Error fetching history:", err);
    }
  };

  const handleDrag = (e) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") {
      setDragActive(true);
    } else if (e.type === "dragleave") {
      setDragActive(false);
    }
  };

  const handleDrop = async (e) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      uploadFile(e.dataTransfer.files[0]);
    }
  };

  const handleFileChange = (e) => {
    if (e.target.files && e.target.files[0]) {
      uploadFile(e.target.files[0]);
    }
  };

  const uploadFile = async (file) => {
    setLoading(true);
    const formData = new FormData();
    formData.append('file', file);
    
    try {
      const res = await fetch(`${API_BASE}/analyze`, {
        method: 'POST',
        body: formData,
      });
      
      if (res.ok) {
        const result = await res.json();
        setSelectedReport(result);
        setActiveTab('summary');
        fetchHistory(); // Refresh history list
      } else {
        const errData = await res.json();
        alert(`Analysis failed: ${errData.error || 'Unknown error'}`);
      }
    } catch (err) {
      console.error("Upload failed:", err);
      alert("Failed to connect to the backend server. Make sure the Flask API is running on port 5000.");
    } finally {
      setLoading(false);
    }
  };

  const selectReport = async (id) => {
    setLoading(true);
    try {
      const res = await fetch(`${API_BASE}/history/${id}`);
      if (res.ok) {
        const data = await res.json();
        setSelectedReport(data);
        setActiveTab('summary');
      }
    } catch (err) {
      console.error("Error fetching report detail:", err);
    } finally {
      setLoading(false);
    }
  };

  const deleteReport = async (e, id) => {
    e.stopPropagation(); // Stop click from selecting the report
    if (!confirm("Are you sure you want to delete this report from your history?")) return;
    
    try {
      const res = await fetch(`${API_BASE}/history/${id}`, {
        method: 'DELETE'
      });
      if (res.ok) {
        fetchHistory();
        if (selectedReport && selectedReport.id === id) {
          setSelectedReport(null);
        }
      }
    } catch (err) {
      console.error("Error deleting report:", err);
    }
  };

  const getFormatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString(lang === 'en' ? 'en-US' : 'fr-FR', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  return (
    <div className="min-h-screen flex flex-col font-sans">
      
      {/* Risk and Safety Layer (Persistent Top Banner) */}
      <div className="bg-red-50 dark:bg-red-950/40 border-b border-red-200 dark:border-red-900/60 py-3 px-4 z-50 transition-colors">
        <div className="max-w-7xl mx-auto flex items-center justify-between gap-3 text-xs md:text-sm text-red-800 dark:text-red-300">
          <div className="flex items-center gap-2">
            <ShieldAlert className="h-5 w-5 flex-shrink-0 text-red-600 dark:text-red-400" />
            <span className="font-medium text-center md:text-left leading-normal">{t.disclaimer}</span>
          </div>
        </div>
      </div>

      {/* Navigation Header */}
      <header className="sticky top-0 bg-white/80 dark:bg-slate-900/80 backdrop-blur-md border-b border-slate-200 dark:border-slate-800 px-6 py-4 z-40 transition-colors">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="h-9 w-9 rounded-lg bg-teal-600 dark:bg-teal-500 flex items-center justify-center text-white font-bold shadow-md shadow-teal-500/20">
              HD
            </div>
            <div>
              <h1 className="text-xl font-bold text-slate-800 dark:text-white flex items-center gap-1.5 leading-none">
                {t.appTitle}
              </h1>
              <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">{t.appSubtitle}</p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            {/* Language Selection */}
            <div className="relative group">
              <button className="p-2 rounded-lg bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 flex items-center gap-1.5 transition-colors">
                <Globe className="h-4.5 w-4.5" />
                <span className="text-xs font-bold uppercase">{lang}</span>
              </button>
              <div className="absolute right-0 mt-2 w-32 bg-white dark:bg-slate-800 rounded-lg shadow-xl border border-slate-200 dark:border-slate-700 py-1 hidden group-hover:block transition-all">
                <button onClick={() => setLang('en')} className="w-full text-left px-4 py-2 text-xs hover:bg-slate-100 dark:hover:bg-slate-700 font-medium">English</button>
                <button onClick={() => setLang('es')} className="w-full text-left px-4 py-2 text-xs hover:bg-slate-100 dark:hover:bg-slate-700 font-medium">Español</button>
                <button onClick={() => setLang('fr')} className="w-full text-left px-4 py-2 text-xs hover:bg-slate-100 dark:hover:bg-slate-700 font-medium">Français</button>
                <button onClick={() => setLang('de')} className="w-full text-left px-4 py-2 text-xs hover:bg-slate-100 dark:hover:bg-slate-700 font-medium">Deutsch</button>
              </div>
            </div>

            {/* Dark/Light Mode Toggle */}
            <button 
              onClick={() => setDarkMode(!darkMode)}
              className="p-2 rounded-lg bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 transition-colors"
            >
              {darkMode ? <Sun className="h-4.5 w-4.5" /> : <Moon className="h-4.5 w-4.5" />}
            </button>
          </div>
        </div>
      </header>

      {/* Main Workspace Dashboard */}
      <main className="flex-1 max-w-7xl w-full mx-auto p-4 md:p-6 grid grid-cols-1 lg:grid-cols-4 gap-6">
        
        {/* Sidebar History Panel */}
        <section className="lg:col-span-1 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-4 flex flex-col h-[600px] lg:h-auto transition-all shadow-sm">
          <div className="flex items-center gap-2 mb-4 border-b border-slate-100 dark:border-slate-800 pb-3">
            <History className="h-5 w-5 text-teal-600 dark:text-teal-400" />
            <h2 className="font-bold text-slate-700 dark:text-white">{t.historyTitle}</h2>
            <span className="ml-auto bg-slate-100 dark:bg-slate-800 px-2 py-0.5 rounded-full text-xs font-semibold text-slate-600 dark:text-slate-400">
              {history.length}
            </span>
          </div>

          <div className="flex-1 overflow-y-auto space-y-2 pr-1">
            {history.length === 0 ? (
              <div className="text-center py-8 text-xs text-slate-400 dark:text-slate-500">
                {t.noHistory}
              </div>
            ) : (
              history.map((rep) => (
                <div 
                  key={rep.id}
                  onClick={() => selectReport(rep.id)}
                  className={`p-3 rounded-lg border text-left cursor-pointer transition-all flex items-start justify-between group ${
                    selectedReport && selectedReport.id === rep.id 
                    ? 'border-teal-500 bg-teal-50/40 dark:bg-teal-950/20' 
                    : 'border-slate-100 hover:border-slate-300 dark:border-slate-800 dark:hover:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-850'
                  }`}
                >
                  <div className="flex-1 min-w-0 pr-2">
                    <p className="text-xs font-bold text-slate-700 dark:text-slate-200 truncate">{rep.filename}</p>
                    <div className="flex items-center gap-2 mt-1">
                      <span className={`text-[10px] px-1.5 py-0.5 rounded font-semibold ${
                        rep.file_type === 'PDF' 
                        ? 'bg-blue-100 text-blue-800 dark:bg-blue-900/40 dark:text-blue-300' 
                        : 'bg-teal-100 text-teal-800 dark:bg-teal-900/40 dark:text-teal-300'
                      }`}>
                        {rep.file_type}
                      </span>
                      <span className="text-[10px] text-slate-400 dark:text-slate-500 truncate">
                        {new Date(rep.created_at).toLocaleDateString(lang, {month: 'short', day: 'numeric'})}
                      </span>
                    </div>
                  </div>
                  <button 
                    onClick={(e) => deleteReport(e, rep.id)}
                    className="text-slate-400 hover:text-red-500 p-1 rounded hover:bg-slate-100 dark:hover:bg-slate-800 opacity-0 group-hover:opacity-100 transition-opacity"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                </div>
              ))
            )}
          </div>

          {selectedReport && (
            <button 
              onClick={() => setSelectedReport(null)}
              className="mt-4 w-full py-2 px-4 rounded-lg bg-teal-600 hover:bg-teal-500 text-white font-bold text-xs flex items-center justify-center gap-2 shadow-md shadow-teal-600/10 transition-colors"
            >
              <Plus className="h-4 w-4" />
              {t.btnNewUpload}
            </button>
          )}
        </section>

        {/* Main Workspace Body */}
        <section className="lg:col-span-3 flex flex-col min-h-[500px]">
          {loading ? (
            <div className="flex-1 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-8 flex flex-col items-center justify-center shadow-sm">
              <Loader2 className="h-10 w-10 text-teal-600 dark:text-teal-400 animate-spin" />
              <p className="mt-4 text-sm font-semibold text-slate-700 dark:text-slate-350 pulse-animation">
                {t.uploadingText}
              </p>
            </div>
          ) : !selectedReport ? (
            /* Upload Center Component */
            <div 
              onDragEnter={handleDrag}
              onDragLeave={handleDrag}
              onDragOver={handleDrag}
              onDrop={handleDrop}
              className={`flex-1 border-2 border-dashed rounded-xl p-8 flex flex-col items-center justify-center text-center transition-all bg-white dark:bg-slate-900 shadow-sm ${
                dragActive 
                ? 'border-teal-500 bg-teal-50/20 dark:bg-teal-950/10' 
                : 'border-slate-350 dark:border-slate-800 hover:border-slate-400'
              }`}
            >
              <div className="h-16 w-16 rounded-full bg-teal-50 dark:bg-teal-950/40 flex items-center justify-center mb-4 text-teal-600 dark:text-teal-400 shadow-inner">
                <UploadCloud className="h-8 w-8" />
              </div>
              <h3 className="text-base font-bold text-slate-700 dark:text-white mb-2">
                {t.uploadZone}
              </h3>
              <p className="text-xs text-slate-400 dark:text-slate-500 max-w-sm mb-6 leading-relaxed">
                {t.uploadFormats}
              </p>
              
              <input 
                type="file" 
                ref={fileInputRef}
                onChange={handleFileChange}
                className="hidden" 
                accept="image/*,application/pdf"
              />
              <button 
                onClick={() => fileInputRef.current?.click()}
                className="px-6 py-2.5 rounded-lg bg-teal-600 hover:bg-teal-500 text-white font-bold text-sm shadow-lg shadow-teal-600/10 hover:shadow-teal-600/20 transition-all transform hover:-translate-y-0.5"
              >
                {t.btnAnalyze}
              </button>
            </div>
          ) : (
            /* Report Analysis Result Viewer */
            <div className="flex-1 flex flex-col gap-6">
              
              {/* Report Title & Toolbar */}
              <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-4 flex flex-col md:flex-row md:items-center justify-between gap-4 shadow-sm transition-all">
                <div className="min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <FileText className="h-5 w-5 text-teal-600 dark:text-teal-400" />
                    <h2 className="font-bold text-slate-800 dark:text-white truncate max-w-md">{selectedReport.filename}</h2>
                    <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-400">
                      {selectedReport.file_type}
                    </span>
                  </div>
                  <div className="flex gap-4 mt-2 text-[10px] text-slate-400 dark:text-slate-500 font-medium">
                    <span>{t.lblDate}: {getFormatDate(selectedReport.created_at)}</span>
                  </div>
                </div>

                <div className="flex items-center gap-2 flex-wrap">
                  <a 
                    href={`${API_BASE}/export/pdf/${selectedReport.id}`}
                    className="flex items-center justify-center gap-1.5 py-1.5 px-3 rounded-lg bg-slate-100 hover:bg-slate-250 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-350 text-xs font-bold transition-colors"
                  >
                    <Download className="h-3.5 w-3.5" />
                    {t.btnExportPdf}
                  </a>
                  <a 
                    href={`${API_BASE}/export/sheet/${selectedReport.id}`}
                    className="flex items-center justify-center gap-1.5 py-1.5 px-3 rounded-lg bg-slate-100 hover:bg-slate-250 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-350 text-xs font-bold transition-colors"
                  >
                    <Stethoscope className="h-3.5 w-3.5" />
                    {t.btnExportSheet}
                  </a>
                </div>
              </div>

              {/* Tab Navigation */}
              <div className="flex items-center border-b border-slate-200 dark:border-slate-850 gap-1 overflow-x-auto">
                <button 
                  onClick={() => setActiveTab('summary')}
                  className={`py-2 px-4 text-xs font-bold whitespace-nowrap transition-all border-b-2 -mb-[2px] ${
                    activeTab === 'summary' 
                    ? 'border-teal-500 text-teal-600 dark:text-teal-400' 
                    : 'border-transparent text-slate-400 dark:text-slate-500 hover:text-slate-600 dark:hover:text-slate-400'
                  }`}
                >
                  {t.tabSummary}
                </button>
                {selectedReport.file_type === 'Image' && (
                  <button 
                    onClick={() => setActiveTab('observations')}
                    className={`py-2 px-4 text-xs font-bold whitespace-nowrap transition-all border-b-2 -mb-[2px] ${
                      activeTab === 'observations' 
                      ? 'border-teal-500 text-teal-600 dark:text-teal-400' 
                      : 'border-transparent text-slate-400 dark:text-slate-500 hover:text-slate-600 dark:hover:text-slate-400'
                    }`}
                  >
                    {t.tabObservations}
                  </button>
                )}
                <button 
                  onClick={() => setActiveTab('findings')}
                  className={`py-2 px-4 text-xs font-bold whitespace-nowrap transition-all border-b-2 -mb-[2px] ${
                    activeTab === 'findings' 
                    ? 'border-teal-500 text-teal-600 dark:text-teal-400' 
                    : 'border-transparent text-slate-400 dark:text-slate-500 hover:text-slate-600 dark:hover:text-slate-400'
                  }`}
                >
                  {t.tabFindings}
                </button>
                <button 
                  onClick={() => setActiveTab('abnormals')}
                  className={`py-2 px-4 text-xs font-bold whitespace-nowrap transition-all border-b-2 -mb-[2px] flex items-center gap-1.5 -mb-[2px] ${
                    activeTab === 'abnormals' 
                    ? 'border-teal-500 text-teal-600 dark:text-teal-400' 
                    : 'border-transparent text-slate-400 dark:text-slate-500 hover:text-slate-600 dark:hover:text-slate-400'
                  }`}
                >
                  {t.tabAbnormals}
                  {(selectedReport.abnormal_values || []).length > 0 && (
                    <span className="bg-red-500 text-white rounded-full text-[9px] w-4.5 h-4.5 flex items-center justify-center font-bold">
                      {(selectedReport.abnormal_values || []).length}
                    </span>
                  )}
                </button>

                <button 
                  onClick={() => setActiveTab('doctor_prep')}
                  className={`py-2 px-4 text-xs font-bold whitespace-nowrap transition-all border-b-2 -mb-[2px] ${
                    activeTab === 'doctor_prep' 
                    ? 'border-teal-500 text-teal-600 dark:text-teal-400' 
                    : 'border-transparent text-slate-400 dark:text-slate-500 hover:text-slate-600 dark:hover:text-slate-400'
                  }`}
                >
                  {t.tabDoctorPrep}
                </button>
              </div>

              {/* Tab Contents */}
              <div className="flex-1 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-6 shadow-sm transition-all">
                
                {/* 1. Summary Tab */}
                {activeTab === 'summary' && (
                  <div className="space-y-4 animate-fade-in">
                    <h3 className="text-base font-bold text-slate-700 dark:text-white flex items-center gap-2">
                      <FileText className="h-4.5 w-4.5 text-teal-600 dark:text-teal-400" />
                      Patient-Friendly Summary
                    </h3>
                    <p className="text-sm text-slate-600 dark:text-slate-300 leading-relaxed bg-slate-50 dark:bg-slate-850 p-4 rounded-xl border border-slate-100 dark:border-slate-800">
                      {selectedReport.summary}
                    </p>
                  </div>
                )}

                {/* 2. Visual Observations Tab (Images Only) */}
                {activeTab === 'observations' && (
                  <div className="space-y-4 animate-fade-in">
                    <div className="p-3 bg-blue-50 dark:bg-blue-950/40 border border-blue-150 dark:border-blue-900/40 rounded-lg text-xs text-blue-800 dark:text-blue-300 flex items-start gap-2">
                      <Info className="h-4 w-4 mt-0.5 flex-shrink-0 text-blue-600 dark:text-blue-400" />
                      <span>{t.disclaimerConfidence}</span>
                    </div>
                    
                    <h3 className="text-base font-bold text-slate-700 dark:text-white flex items-center gap-2">
                      <Eye className="h-4.5 w-4.5 text-teal-600 dark:text-teal-400" />
                      Visual Observations
                    </h3>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      {(selectedReport.observations || []).map((obs, idx) => (
                        <div key={idx} className="border border-slate-150 dark:border-slate-800 p-4 rounded-xl hover:shadow-md transition-all">
                          <h4 className="text-sm font-bold text-slate-800 dark:text-white flex items-center gap-1.5">
                            <span className="h-2 w-2 rounded-full bg-teal-500"></span>
                            {obs.title}
                          </h4>
                          <p className="text-xs text-slate-600 dark:text-slate-400 mt-2 leading-relaxed">
                            {obs.description}
                          </p>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* 3. Key Findings Tab */}
                {activeTab === 'findings' && (
                  <div className="space-y-4 animate-fade-in">
                    <h3 className="text-base font-bold text-slate-700 dark:text-white flex items-center gap-2">
                      <Activity className="h-4.5 w-4.5 text-teal-600 dark:text-teal-400" />
                      {t.secObservations}
                    </h3>
                    
                    <ul className="space-y-3">
                      {(selectedReport.observations || []).map((obs, idx) => (
                        <li key={idx} className="flex items-start gap-3 p-3 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-850 transition-colors">
                          <div className="mt-0.5 rounded-full bg-teal-100 text-teal-800 dark:bg-teal-900/60 dark:text-teal-350 p-1 flex items-center justify-center">
                            <CheckCircle className="h-3.5 w-3.5" />
                          </div>
                          <div>
                            <span className="text-sm font-bold text-slate-800 dark:text-white">{obs.title}</span>
                            <p className="text-xs text-slate-500 dark:text-slate-455 mt-1">{obs.description}</p>
                          </div>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {/* 4. Abnormal Values Tab */}
                {activeTab === 'abnormals' && (
                  <div className="space-y-4 animate-fade-in">
                    <h3 className="text-base font-bold text-slate-700 dark:text-white flex items-center gap-2">
                      <AlertTriangle className="h-4.5 w-4.5 text-red-500" />
                      {t.lblAbnormalDetected}
                    </h3>
                    
                    {(selectedReport.abnormal_values || []).length === 0 ? (
                      <div className="text-center py-8 text-xs text-slate-400 dark:text-slate-500">
                        No values outside standard reference ranges were identified.
                      </div>
                    ) : (
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        {(selectedReport.abnormal_values || []).map((val, idx) => (
                          <div key={idx} className="border-l-4 border-red-500 bg-red-50/20 dark:bg-red-950/10 border border-slate-200 dark:border-slate-800 p-4 rounded-xl transition-all">
                            <div className="flex justify-between items-start">
                              <h4 className="text-sm font-bold text-slate-800 dark:text-white">{val.parameter}</h4>
                              <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-red-100 text-red-800 dark:bg-red-900/40 dark:text-red-300">
                                {t.lblValue}: {val.value}
                              </span>
                            </div>
                            <p className="text-[10px] text-slate-400 dark:text-slate-500 mt-1">
                              {t.lblNormal}: {val.reference_range}
                            </p>
                            <div className="mt-3 text-xs bg-white dark:bg-slate-850 p-2.5 rounded-lg border border-slate-100 dark:border-slate-800 text-slate-650 dark:text-slate-355 leading-relaxed">
                              <strong>{t.lblInterpretation}:</strong> {val.interpretation}
                            </div>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                )}

                {/* 6. Doctor Visit Prep */}
                {activeTab === 'doctor_prep' && (
                  <div className="space-y-6 animate-fade-in">
                    
                    {/* Checklist of customized questions */}
                    <div className="space-y-3">
                      <h3 className="text-sm font-bold text-slate-700 dark:text-white flex items-center gap-2 border-b border-slate-100 dark:border-slate-800 pb-2">
                        <Stethoscope className="h-4 w-4 text-teal-600 dark:text-teal-400" />
                        {t.secQuestions}
                      </h3>
                      <p className="text-xs text-slate-400 dark:text-slate-500 leading-normal">
                        Print out or open this checklist when speaking to your consulting physician to address key findings:
                      </p>
                      
                      <div className="space-y-2">
                        {(selectedReport.doctor_questions || []).map((q, idx) => (
                          <div key={idx} className="flex items-start gap-3 p-3 rounded-lg border border-slate-100 dark:border-slate-800 hover:border-slate-200 transition-all">
                            <input 
                              type="checkbox" 
                              id={`q-${idx}`}
                              className="mt-1 h-4 w-4 rounded border-slate-350 text-teal-600 focus:ring-teal-500"
                            />
                            <label htmlFor={`q-${idx}`} className="text-xs text-slate-700 dark:text-slate-300 font-medium leading-relaxed select-none cursor-pointer">
                              {q}
                            </label>
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Symptoms to Mention printable notes area */}
                    <div className="space-y-3">
                      <h3 className="text-sm font-bold text-slate-700 dark:text-white flex items-center gap-2 border-b border-slate-100 dark:border-slate-800 pb-2">
                        <Activity className="h-4 w-4 text-teal-600 dark:text-teal-400" />
                        {t.secSymptoms}
                      </h3>
                      <p className="text-xs text-slate-400 dark:text-slate-500 leading-normal">
                        Before your doctor's visit, write down any symptoms (e.g. fatigue, localized pain, shortness of breath) or relevant medication history here:
                      </p>
                      <textarea 
                        className="w-full min-h-[80px] p-3 rounded-lg border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-850 text-xs focus:ring-1 focus:ring-teal-500 focus:outline-none placeholder-slate-400"
                        placeholder="E.g., I've been feeling unusually tired for the past two weeks, and sometimes experience dry cough in the mornings."
                      />
                    </div>
                  </div>
                )}

              </div>
            </div>
          )}
        </section>
        
      </main>

      {/* Footer */}
      <footer className="bg-white dark:bg-slate-900 border-t border-slate-200 dark:border-slate-800 py-6 px-4 text-center text-xs text-slate-400 dark:text-slate-500 transition-all mt-auto">
        <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <p>&copy; {new Date().getFullYear()} {t.appTitle} - Medical Second-Opinion Companion.</p>
          <div className="flex gap-4">
            <span className="font-semibold text-teal-600 dark:text-teal-400">HealthDecode AI</span>
            <span>&bull;</span>
            <span>Offline Encryption Enabled</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
